### PR TITLE
Created Articles Model and Relationship to Categories

### PR DESCRIPTION
**Pull request by ConlonNovak**
I went ahead and added content to the Articles model, as instructed. I really hope that I haven't forgotten anything essential, like 2/3 of MVC.

### CODE REVIEW

**Comment by abbeymui** [comment]
I just have some thoughts that are very original....I really like the idea of adding articles, but I think it needs more than just the models before I can make a decision. After all, Rails is all about MVC working together, not just the M portion in isolation. If the views and controller are in working order, then I'll pull this into my project.

**Comment by abbeymui** [comment]
wow! I said the same thing just a few minutes ago about another project. Check again now.

**Comment by ConlonNovak** [comment]
Everything should be ship-shape now! Test this and merge my changes if it works!

**Comment by abbeymui** [comment]
It doesn't work :( some errors when I try to migrate; pls check

**Comment by ConlonNovak** [comment]
Hey - I was working on some fixes while you were reviewing, try the f81f762 commit if you haven't already. Worked for me locally.

**Pull request merged**
